INSERT INTO PUBLIC.USERS (ID, DESCRIPTION, EMAIL, NEWSLETTER_SUBSCRIBER, PASSWORD, PICTURE, USERNAME) VALUES (33, null, 'wesh@test.com', false, '$2a$10$xK9uEDUp53/UPawVt9Gvu.CBxFKP43mJ5R6G9LLmf4iZachdgX3ZS', 'https://64.media.tumblr.com/94638a78ebb2f474b5539aee168af44d/tumblr_mxy2k79HUl1smqdb1o1_400.gifv', 'SaladeTomateOignon');
INSERT INTO PUBLIC.USERS (ID, DESCRIPTION, EMAIL, NEWSLETTER_SUBSCRIBER, PASSWORD, PICTURE, USERNAME) VALUES (97, 'Je suis le fameux Louis Binaire, le seul, l''unique, celui qui calcule plus vite que son ombre', 'louisbinaire@gmail.com', false, '$2a$10$eW3bKXZ76PsYYbhWTkhQ6eNFgItLuFPK30Lr1cLA7nAvFRgHkxsLa', 'https://www.gifimili.com/gif/2018/02/bob-l-eponge-arc-en-ciel.gif', 'LouisBinaire');
INSERT INTO PUBLIC.USERS (ID, DESCRIPTION, EMAIL, NEWSLETTER_SUBSCRIBER, PASSWORD, PICTURE, USERNAME) VALUES (162, null, 'bg77@uge.fr', false, '$2a$10$XrQ26WI918hMoO5PET.xSO04bN14/H6HuSDfX7go42o8y2jMT7FsS', null, 'Hoomar');
INSERT INTO PUBLIC.USERS (ID, DESCRIPTION, EMAIL, NEWSLETTER_SUBSCRIBER, PASSWORD, PICTURE, USERNAME) VALUES (205, 'Oh si.... c''est rigolo ....', 'pedrojuan@gmail.com', false, '$2a$10$l2WZzWGZGs1DAWbaJJDoA./VuI8NDdLKrSgDBVZbXLWe4WCXEZJwa', 'https://risibank.fr/cache/stickers/d2254/225426-full.png', 'PedroJuan');
INSERT INTO PUBLIC.USERS (ID, DESCRIPTION, EMAIL, NEWSLETTER_SUBSCRIBER, PASSWORD, PICTURE, USERNAME) VALUES (213, 'A Dinosaur who deserve a good mark for this project and love his teacher from the bottom of his heart', 'ElTiernausore@gmail.com', false, '$2a$10$7qjD0UTzUZUur3U1zO8XQuDA6J9g6l68csMHyfGcEHlfL.A634TkW', 'https://www.leparisien.fr/resizer/e_ONnK23oLDMJT3CLusiA2W3dB8=/932x582/arc-anglerfish-eu-central-1-prod-leparisien.s3.amazonaws.com/public/WS2SPBO64DI5XPEQL5ADGIVTZA.jpg', 'ElTiernausore');
INSERT INTO PUBLIC.USERS (ID, DESCRIPTION, EMAIL, NEWSLETTER_SUBSCRIBER, PASSWORD, PICTURE, USERNAME) VALUES (233, 'Best Java developper you ever seen', 'DarkSasuke77@gmail.com', false, '$2a$10$xImW7rIU3r.AcnnyMc3aG.NPNYpx/HQuWOLff1EBKqm.v4gFO/k4q', 'https://avatars.githubusercontent.com/u/828220?s=400&v=4', 'RemiForax');
INSERT INTO PUBLIC.USERS (ID, DESCRIPTION, EMAIL, NEWSLETTER_SUBSCRIBER, PASSWORD, PICTURE, USERNAME) VALUES (235, 'Mon language prefere et que je maitrise le plus: HTML
Un peu le CSS aussi mais c''est dur ', 'DevPasTerrible@gmail.com', false, '$2a$10$t/d6ShAEWY6XBpxovZVbq.4tW30Ulwdckgz5.7xyrj7p9BP6m.bwm', 'https://media.tenor.com/images/0c95b6e7c5d7fa56ea7b84f8b981d147/tenor.gif', 'DevPasTerrible');
INSERT INTO PUBLIC.USERS (ID, DESCRIPTION, EMAIL, NEWSLETTER_SUBSCRIBER, PASSWORD, PICTURE, USERNAME) VALUES (283, null, 'tototaka@gmail.com', false, '$2a$10$EfRLQnT9Ymv6pq6mct8fce3fH/CnH6aIn1J/EjPw/eVM59zvkSi1e', 'https://static1.purebreak.com/articles/8/87/71/8/@/397790-un-chien-qui-trolle-avec-ses-faux-624x0-1.jpg', 'tototaka');
INSERT INTO PUBLIC.USERS (ID, DESCRIPTION, EMAIL, NEWSLETTER_SUBSCRIBER, PASSWORD, PICTURE, USERNAME) VALUES (284, null, 'admin@reddigm.fr', false, '$2a$10$.JUY/yYY5eb6oSBFUMDCZONthl/1F7watZbMo7RTnKrOuWN0UmW3e', '', 'admin');
INSERT INTO PUBLIC.USERS (ID, DESCRIPTION, EMAIL, NEWSLETTER_SUBSCRIBER, PASSWORD, PICTURE, USERNAME) VALUES (348, null, 'toto@gmail.com', false, '$2a$10$B1rzC5vEyVq0/sDT1OXAQOw8.ZpuUP9z3MIcNAoHOx/0RgimDL/pq', 'https://pbs.twimg.com/media/EeU1cJzX0AAHUUO.jpg', 'Toto');